run:
	python findweb.py projects http://www2.hawaii.edu/~esb/2022spring.ics651/project3.html
	
run:
	python findweb.py projects http://www2.hawaii.edu/~esb/2022spring.ics651/project3.html -r

setup: requirements.txt
	pip install -r requirements.txt
	
clean:
	rm -rf _pycache_